name: CI

on:
  push:
    branches:
      - main
      - feature-carrier
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      -
        name: Start services
        run: docker compose up --wait --no-build
      -
        name: Check HTTP reachability
        run: curl -L -v --head --fail -o /dev/null http://localhost
      -
        name: Check HTTPS reachability
        run: wget -O /dev/null https://localhost
      -
        name: Install Symfony Runtime
        run: docker compose exec -T php composer require symfony/runtime
      -
        name: Wait for Symfony to Start
        run: docker compose exec -T php bin/console doctrine:query:sql "SELECT 1" --env=test
      -
        name: Create test database
        run: docker compose exec -T php bin/console doctrine:database:create --env=test
      -
        name: Run migrations
        run: docker compose exec -T php bin/console doctrine:migrations:migrate --no-interaction --env=test
      -
        name: Run PHPUnit
        run: docker compose exec -T php vendor/bin/phpunit
      -
        name: Doctrine Schema Validator
        run: docker compose exec -T php bin/console doctrine:schema:validate --env=test
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
